### PR TITLE
[docs] add badges

### PR DESCRIPTION
**Pull request by ggurkal**
added github release badge and npm badge. feel free to add more if you think of any.

### CODE REVIEW

**Comment by mitchelvanbever** [comment]
I see one badge correct? Npm would be downloads I suppose? On the other repos we have github stars as well. Don't think codesandbox of the visual studio browser are needed here.

**Comment by leeuwis** [comment]
I think the stars are unnecessary since you can already see them on top @mitchelvanbever. Codecov would be a nice addition imo, but can’t get it to load the storyofams repos after authorizing the organization for some reason (infinite spinner)..

**Comment by mitchelvanbever** [comment]
> Codecov would be a nice addition imo, but can’t get it to load the storyofams repos after authorizing the organization for some reason (infinite spinner)..

That's because we don't use codecov ? 😅 you can probably achieve the same without codecov by uploading coverage in the github action to run tests.

In regards to the stars; I just want uniformity. Maybe we can come up with 2-3 badges we're using apart from the codesandbox one if that makes sense. Which would mean we'd drop the stars on all repo's

**Review by leeuwis — APPROVED** [review]

**Review by leeuwis — COMMENTED** [review]
My suggestions:
- Add `<a>` tags around the badges like in `next-boilerplate`
- Adding the stargazer badge (as the most right badge)

We can add the codecov badge when #24 is merged.

**Review by leeuwis — APPROVED** [review]

**Pull request merged**
