### PR TITLE
[docs] intro in readme & table of contents

### PR DESCRIPTION
**Pull request by ggurkal**
* Add Table of Contents
* Add basic introduction, so people are first going to see how the library works.

Question: The introduction is like a comparison, but should we keep it like this or just show how the library works without the comparison?

### CODE REVIEW

**Comment by mitchelvanbever** [comment]
To me it feels a little weird that the table of contents comes after the introduction.

**Comment by ggurkal** [comment]
The idea is to show devs/users how it works first, before going to the ToC and other stuff. I don't have a strict opinion about it though...

**Comment by mitchelvanbever** [comment]
I think [this](https://github.com/joshbuchea/HEAD) and [this one](https://github.com/webpack/webpack) are IMO very clean looking README's.

@leeuwis any opinions on the order of content?

**Comment by mitchelvanbever** [comment]
Firefox Developer Edition-storyofamsnext-api-decorators Collection of decorators to create typed Next js API routes, with easy request validation and transformation _2021-03-28

This new feature pretty much renders my previous comment useless. I would say all good to go as is 👍

**Review by mitchelvanbever — APPROVED** [review]

**Comment by leeuwis** [comment]
- Is the table of contents still relevant with the new GitHub feature?
- I would start with the usage example (the outcome), so it's immediately clear what kind of decorators the package offers. Someone is probably looking for the repo since they know the pain of writing API routes without it.
- Then I would add the example of how would look without it after the outcome (so what you now have as the first example) in a collapsible area. Might be good to also add some validation in the "without decorators" example like `return res.status(400).json({ statusCode: 400, message: 'Email is required' })`
- For the sake of the example, I would remove the first import line from both intro examples.

**Comment by ggurkal** [comment]
> Is the table of contents still relevant with the new GitHub feature?

Seems that Table of Contents is not necessary in GitHub, but the same readme file will be in NPM as well. 🤔 

--

> Might be good to also add some validation in the "without decorators" example

This can be in the collapsible but I'm afraid adding it to our first appeal code will make it longer. I think we can simply add the `ValidationPipe` and add a link into the text like ***Read more about validation [link]here[/link]***

**Comment by mitchelvanbever** [comment]
> Seems that Table of Contents is not necessary in GitHub, but the same readme file will be in NPM as well. 🤔

Yeah but I agree that NPM should be more catchy, probably if you really wanna know more you'll go the github page from the NPM page. Or at least that is most of the time what I do.

> This can be in the collapsible but I'm afraid adding it to our first appeal code will make it longer. I think we can simply add the ValidationPipe and add a link into the text like Read more about validation [link]here[/link]

Sounds like the perfect plan to me 😃

**Comment by leeuwis** [comment]
Structure look nice like this imo! Maybe a header above the first example like `Basic usage`, and I think it's good to go 👌

**Pull request merged**
